language: php

php:
  - 7.2
  - 7.4
  - 'nightly'

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 5.6
      env: PHP56=1 DEFAULT=0

install:
  - composer install --no-interaction

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHP56 == 1 ]]; then vendor/bin/phpunit tests/php56/; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p -n --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

notifications:
  email: false
