language: php

php:
  - 7.2
  - 7.4

matrix:
  include:
    - php: 7.2
      env: PHPCS=1

before_script: composer install

script:
  - if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -p -n --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

notifications:
  email: false
