language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script: composer install --prefer-dist --dev

script: phpunit

notifications:
  email: false
