---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  testsuite-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['5.6', '7.4', '8.0']
        prefer-lowest: ['']
        include:
          - php-version: '5.6'
            prefer-lowest: 'prefer-lowest'

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Get date part for cache key
      id: key-date
      run: echo "::set-output name=date::$(date +'%Y-%m')"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.key-date.outputs.date }}-${{ hashFiles('composer.json') }}-${{ matrix.prefer-lowest }}

    - name: Composer install
      run: |
        if [[ ${{ matrix.php-version }} == '8.0' ]]; then
          composer install --ignore-platform-reqs
        elif ${{ matrix.prefer-lowest == 'prefer-lowest' }}; then
          composer update --prefer-lowest --prefer-stable
        else
          composer install
        fi

    - name: Run PHPUnit
      run: |
        if [[ ${{ matrix.php-version }} == '5.6']]; then
          vendor/bin/phpunit tests/php56/
        else
          vendor/bin/phpunit
        fi

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: none
        tools: psalm:~4.1.0

    - name: Composer Install
      run: composer install

    - name: Run phpcs
      run: vendor/bin/phpcs -p src/ tests/

    - name: Run psalm
      run: psalm --output-format=github
